/* eslint-disable import/no-cycle */
import {
  HEADER_TITLE,
  CONSTANTS,
  CTA_LABELS,
  ERRORS,
  CLASSES,
  ALT_CONSTANTS,
  INPUT_CONSTANTS,
  GATTING_CRITERIA,
  PROGRESS_BAR_CONSTANT,
  READ_MORE_EXPAND_TITLES,
  ISAUTHORISED_CHECKBOXES_IDENTITY,
  ISCONDITION_CHECKBOXES_IDENTITY,
  NOTES,
  LOCAL_STORAGE_HOTEL,
  LOCAL_STORAGE_HOTEL_ON_UNLOAD,
  SOMETHING_WENT_WRONG,
  BENEFITS,
  LOGIN_PRODUCT_ITEMS,
  GENRAL_TERM_AND_CONDI,
  AMBER_ERROR_BANK_MASSEGE,
  IS_TREM_CHECKBOXES,
  IS_TREM_CHECKBOXES_FOR_INDIFI,
  getStepsTL,
  REDIRECT_LIST_DATA,
  ProcessingRequest,
  BankStatementUploadNote,
  TURNOVERMONTHLYSALES,
  TURNOVERMONTHLYSALESPRE,
  FIRST_LOGIN_NUMBER,
  DOC_CATEGRIES_LIST,
  SanctionLetterUploadNote,
  ITRRETURNUploadNote,
  LENDINGKARTNAMENote,
  LENDERNAMEINDIFINote,
  selectLenderCard
} from './eng';

// import {
//   HEADER_TITLE,
//   CONSTANTS,
//   CTA_LABELS,
//   ERRORS,
//   CLASSES,
//   ALT_CONSTANTS,
//   INPUT_CONSTANTS,
//   GATTING_CRITERIA,
//   PROGRESS_BAR_CONSTANT,
//   READ_MORE_EXPAND_TITLES,
//   ISAUTHORISED_CHECKBOXES_IDENTITY,
//   ISCONDITION_CHECKBOXES_IDENTITY,
//   NOTES,
//   LOCAL_STORAGE_HOTEL,
//   LOCAL_STORAGE_HOTEL_ON_UNLOAD,
//   SOMETHING_WENT_WRONG,
//   BENEFITS,
//   LOGIN_PRODUCT_ITEMS,
//   GENRAL_TERM_AND_CONDI,
//   AMBER_ERROR_BANK_MASSEGE,
//   IS_TREM_CHECKBOXES,
//   getStepsTL,
//   REDIRECT_LIST_DATA
//   ProcessingRequest,
//   BankStatementUploadNote
// TURNOVERMONTHLYSALES
// TURNOVERMONTHLYSALESPRE
// } from './hin';

const CLEVERTAP_EVENTS = {
  PAGE_LOADS: {
    MOBILE_PAGE: 'TL_login_page_load',
    OTP_PAGE: 'TL_login_page_load',
    NWL_PAGE: 'TL_non_whitelist_user_rejected_page_load',
    OFFER_EXPIRED_PAGE: 'TL_offer_expired_page_load',
    WELCOME_PAGE: 'TL_welcome_page_load',
    BASIC_INFO_PAGE: 'TL_basic_info_page_load',
    BASIC_INFO_ERROR_PAGE: 'TL_basic_info_rejected_page_load',
    ENTER_PAN_PAGE: 'TL_enter_PAN_page_load',
    PRE_FILLED_PAN_PAGE: 'TL_pre_filled_PAN_page_load',
    PAN_ERROR_PAGE: 'TL_PAN_rejected_page_load',
    PAN_VALIDATION_FAILED: 'TL_PAN_validation_failed_page_load',
    NON_PROPRIETOR_PAN_ENTER: 'TL_non_proprietor_pan_enter',
    PERSONAL_INFO_PAGE: 'TL_personal_info_page_load',
    PERSONAL_INFO_ERROR_PAGE: 'TL_personal_info_rejected_page_load',
    REDIRECT_PAGE: 'TL_redirect_page_load',
    ADDRESS_PAGE: 'TL_address_page_load',
    ADDRESS_ERROR_PAGE: 'TL_address_rejected_page_load',
    OFFLINE_WEBHOOK_FLOW_PAGE: 'TL_offline_flow_page_load',
    OFFLINE_WEBHOOK_ERROR_PAGE: 'TL_offline_flow_rejected_page_load',
    INDIFI_BRE_ERROR_PAGE: 'TL_indifi_bre_rejected_page_load',
    REDIRECT_INDIFI_PAGE: 'TL_indifi_redirect_page_load',
    INDIFI_AMOUNT_PAGE_LOAD: 'TL_indifi_amount_page_load',
    INDIFI_UPLOAD_STATEMENT_PAGE_LOAD: 'TL_indifi_page_statement_page_load',
    DISBURSE_AMOUNT_PAGE_LOAD: 'TL_disburse_amount_page_load',
    REJECTED_PAGE_LOAD: 'TL_rejected_page_load',
  },
  CTA_CLICKS: {
    MOBILE_CTA: 'TL_login_cta_click',
    OTP_CTA: 'TL_login_cta_click',
    NWL_CTA: 'TL_NWL_cta_click',
    OFFER_EXPIRED_CTA: 'TL_offer_expired_cta_click',
    WELCOME_JOURNEY_CREATE_CTA: 'TL_welcome_journey_create_cta_click',
    WELCOME_JOURNEY_UPDATE_CTA: 'TL_welcome_journey_update_cta_click',
    BASIC_INFO_CTA: 'TL_basic_info_cta_click',
    BASIC_INFO_ERROR_CTA: 'TL_basic_info_rejected_logout_cta_click',
    ENTER_PAN_CTA: 'TL_enter_pan_cta_click',
    PAN_VALIDATION_FAILED_CTA: 'TL_pan_validation_falied_cta_click',
    PAN_ERROR_CTA: 'TL_pan_rejected_logout_cta_click',
    NON_PROPRIETOR_PAN_CTA: 'TL_non_proprietor_pan_cta_click',
    PERSONAL_INFO_CTA: 'TL_personal_info_cta_click',
    PERSONAL_INFO_ERROR_CTA: 'TL_personal_info_rejected_logout_cta',
    REDIRECT_CTA: 'TL_redirect_cta_click',
    ADDRESS_CTA: 'TL_address_cta_click',
    ADDRESS_ERROR_CTA: 'TL_address_rejected_logout_cta_click',
    OFFLINE_WEBHOOK_ERROR_CTA: 'TL_offline_webhook_rejected_logout_cta_click',
    INDIFI_BRE_ERROR_CTA: 'TL_indifi_bre_rejected_logout_cta_click',
    INDIFI_REDIRECT: 'TL_indifi_bre_rediect_to_indifi',
    INDIFI_AMOUNT_CTA_CLICL: 'TL_indifi_amount_cta_click',
    INDIFI_AMOUNT_BANK_STATEMENT_CTA_CLICL: 'TL_indifi_amount_bank_statement_cta_click',
    INDIFI_REDIRECTION_UPDATED_API_CALLED: 'TL_indifi_rediect_update_api_called',
    INDIFI_UPLOAD_STATEMENT_CTA: 'TL_indifi_page_statement_cta_clicked',
    DISBURSE_AMOUNT_CTA: 'TL_disburse_For_all_Lender_CTA_Clicked',
    REJECTED_CTA: 'TL_rejected_cta_clicked',
  },
  COMMON: {
    API_FAILURE: 'TL_api_failure',
    LOGIN_SUCCESSFULL: 'TL_login_successfull',
  },
};

export {
  HEADER_TITLE,
  CONSTANTS,
  CTA_LABELS,
  ERRORS,
  CLASSES,
  ALT_CONSTANTS,
  INPUT_CONSTANTS,
  GATTING_CRITERIA,
  PROGRESS_BAR_CONSTANT,
  READ_MORE_EXPAND_TITLES,
  ISAUTHORISED_CHECKBOXES_IDENTITY,
  ISCONDITION_CHECKBOXES_IDENTITY,
  NOTES,
  LOCAL_STORAGE_HOTEL,
  LOCAL_STORAGE_HOTEL_ON_UNLOAD,
  SOMETHING_WENT_WRONG,
  BENEFITS,
  LOGIN_PRODUCT_ITEMS,
  GENRAL_TERM_AND_CONDI,
  AMBER_ERROR_BANK_MASSEGE,
  CLEVERTAP_EVENTS,
  IS_TREM_CHECKBOXES,
  IS_TREM_CHECKBOXES_FOR_INDIFI,
  getStepsTL,
  REDIRECT_LIST_DATA,
  ProcessingRequest,
  BankStatementUploadNote,
  TURNOVERMONTHLYSALES,
  TURNOVERMONTHLYSALESPRE,
  FIRST_LOGIN_NUMBER,
  DOC_CATEGRIES_LIST,
  SanctionLetterUploadNote,
  ITRRETURNUploadNote,
  LENDINGKARTNAMENote,
  LENDERNAMEINDIFINote,
  selectLenderCard
};
